version: '1.0'
name: generate-pages
displayName: GeneratePages
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
  schedule:
    - cron: '* 5 8 * * ? *'
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - npm  remove --global @hz-9/docs-build @microsoft/api-documenter @microsoft/api-extractor
          - npm  --registry https://registry.npmmirror.com/ install --global @hz-9/docs-build @microsoft/api-documenter@7.25.3 @microsoft/api-extractor@7.46.2
          - node ./common/scripts/install-run-rush.js update
          - docs-build --action build --base-url '/a4/' --lang en-US,zh-CN
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vuepress/src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.rush
          - ./.pnpm-store
          - ./docs/.vuepress/node_modules
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: pages
        dependsOn: build_nodejs
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: hz-9
          hostID:
            - ae5f4645-c72c-407f-8377-7033c8e79165
        deployArtifact:
          - source: artifact
            name: pages
            target: /usr/heaven_docs/a4
            artifactRepository: default
            artifactName: pages
            artifactVersion: latest
        script:
          - cd /usr/heaven_docs/a4
          - tar zxvf pages.tar.gz
          - cd ../ && rm -rf ./a4_dist
          - mv ./a4/dist ./a4_dist
          - rm -rf ./a4/*
          - mv ./a4_dist/* ./a4/
          - echo 'Publish Page Complete!'
        notify: []
        strategy:
          retry: '0'
strategy:
  cloneDepth: 1
  blocking: true
